### PR TITLE
Documentation & README Changes

### PR DESCRIPTION
**Pull request by badwolfbit**
- removed package-lock.json due to potential errors
- moved documentation assets (ex. gif screenshot) to the documentation folder directory
- moved artillery & loader.io assets to test folder directory
- updated README to include "Getting Started" & screenshot source directory change

### CODE REVIEW

**Comment by badwolfbit** [comment]
Hey @CodeWritingCow, I did some initial cleanup for stuff feel free to review

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
@omenwolf thank you for the PR! Can you address a couple issues before I approve the PR?

1. Can you restore the `GET` route for the loader.io token to its original URL? For the token to work, loader.io requires a specific URL. See https://support.loader.io/article/20-verifying-an-app
2. Does `artillery-test.yml` still work after moving into the new directory `test`?
3. Should the instructions in README.md be more explicit? For example, "Type `npm install` in command console" versus just "`npm install`"

Thanks again!

**Comment by badwolfbit** [comment]
@CodeWritingCow I restored the load.io token file to the root directory, in the future we can consolidate the tests into the "test" folder directory

artillery.js runs well with the .yml file in the test folder directory
suggest doing cmd, `artillery run test/artillery-test.yml`

The cmd notes on the README should be fine as is. 
it looks self-explanatory when mentioning `npm install`...

**Comment by CodeWritingCow** [comment]
@omenwolf thanks!

**Pull request merged**
