### PR TITLE
Express Routes

### PR DESCRIPTION
**Pull request by badwolfbit**
New Server file folder directory

Following Changes:

index.js
Using express routes offering modularity to Node.js server

routes
- api-route.js (empty)
- error-route.js
- index-route.js
- middleware-route.js
- search-route.js
- violation_report-route.js

controller
- api-controller.js (empty)
- error-controller.js
- index-controller.js
- search-controllers.js (get & post)
- violation_report-controller.js

### CODE REVIEW

**Comment by badwolfbit** [comment]
Hey @CodeWritingCow, added some modularity to the back-end

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
@omenwolf this PR is great. It makes the Node.js server much more modular and maintainable. Thank you. 

Before I merge the PR, I have a question.

- `api-routes.js` and `api-controller.js` are empty. What are their purposes?

Also, can you clean up the following?
- Since `index.js` has replaced `server.js`, the latter is no longer needed. Let's delete `server.js`.
- Can you add semicolons to end of these lines? https://github.com/omenwolf/NYC-restaurant-inspection-records/blob/3e38067a55cde9e2e38b51fd67abe01309b1f358/server/index.js#L22-L25

**Comment by badwolfbit** [comment]
@CodeWritingCow sure no problem!
`api-route.js` & `api-controller.js` are currently placeholders for the API call, however, I'm currently unsure how to properly implement them as the API is called on the `/search` endpoint. We can discuss this during our standup meeting.

I'll enact the following changes suggested:
- removing `server.js` from root directory
- including semicolons on the `index.js` route calls.

**Comment by CodeWritingCow** [comment]
Looks good @omenwolf!

**Pull request merged**
