### PR TITLE
React base search page

### PR DESCRIPTION
**Pull request by CodeWritingCow**
Convert advanced search form from Handlebars to React.

### CODE REVIEW

**Comment by CodeWritingCow** [comment]
### React version of search form
Screen Shot 2019-07-11 at 1 41 54 PM

Screen Shot 2019-07-11 at 1 42 37 PM

**Comment by CodeWritingCow** [comment]
### Original Handlebars version

Screen Shot 2019-07-11 at 1 42 13 PM

Screen Shot 2019-07-11 at 1 43 03 PM

The HBS menu gets its Material Design look from a Materialize plugin. I can look into implementing the plugin with React.

**Comment by badwolfbit** [comment]
React Component:
Screenshot 2019-07-11 14 26 17
Handlebars Component:
Screenshot 2019-07-11 14 26 07


##### @CodeWritingCow are we going for a design change on the "advanced search" subpage?

**Comment by CodeWritingCow** [comment]
@omenwolf no design change for now. The PR focuses on functionality only. Let's make the React form look more like the original form.

**Comment by badwolfbit** [comment]
Will merge. Next, on the tracker is CSS styling with Materialize

**Pull request merged**
